# Generated by Django 4.2.7 on 2024-03-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=122)),
                ('lname', models.CharField(max_length=122)),
                ('useremail', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
    ]
