# Generated by Django 4.2.7 on 2024-03-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='useremail',
            new_name='username',
        ),
    ]
