# Generated by Django 4.2.7 on 2024-03-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_useremail_signup_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='email',
        ),
    ]
