# Generated by Django 4.2.7 on 2024-03-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_username_signup_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='lname',
            new_name='username',
        ),
    ]
