# Generated by Django 4.2.7 on 2024-04-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=122)),
                ('number', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
            ],
        ),
    ]
