# Generated by Django 4.2.7 on 2024-04-01 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_book_edate_remove_book_sdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='book',
            name='sdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
