# Generated by Django 4.2.7 on 2024-04-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_contact_email_alter_myuser_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
