# Generated by Django 4.2.7 on 2024-04-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
