# Generated by Django 4.2.7 on 2024-04-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carmodel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
